from conarch.sound_change_rule import SoundChangeRule
from conarch.sound import Sound
from conarch.language import Language
from conarch import db
from conarch.word_form_rule import WordFormRule


# noinspection SpellCheckingInspection
def generate_koa():
    koa_sounds = list()

    koa_a = Sound('a', 'ä', 'V', 17)
    koa_sounds.append(koa_a)
    koa_e = Sound('e', 'e', 'V', 6)
    koa_sounds.append(koa_e)
    koa_i = Sound('i', 'i', 'V', 8)
    koa_sounds.append(koa_i)
    koa_o = Sound('o', 'o̞', 'V', 4)
    koa_sounds.append(koa_o)
    koa_u = Sound('u', 'ʊ', 'Vu', 7)
    koa_sounds.append(koa_u)

    koa_p = Sound('p', 'p', 'SOC', 0.7)
    koa_sounds.append(koa_p)
    koa_t = Sound('t', 't', 'SOC', 4)
    koa_sounds.append(koa_t)
    koa_k = Sound('k', 'k', 'SOC', 4.5)
    koa_sounds.append(koa_k)
    koa_q = Sound('q', 'q', 'SOC', 1)
    koa_sounds.append(koa_q)
    koa_glottalstop = Sound("'", 'ʔ', 'SOC', 5)
    koa_sounds.append(koa_glottalstop)
    koa_b = Sound('b', 'ɓ', 'SOC', 3)
    koa_sounds.append(koa_b)
    koa_tejective = Sound("t'", 't’', 'SOEC', 0.4)
    koa_sounds.append(koa_tejective)
    koa_kejective = Sound("k'", 'k’', 'SOEC', 1)
    koa_sounds.append(koa_kejective)

    koa_c = Sound('c', 't͡s', 'AOC', 1.5)
    koa_sounds.append(koa_c)
    koa_cejective = Sound("c'", 't͡sʼ', 'AOEC', 0.3)
    koa_sounds.append(koa_cejective)
    koa_ch = Sound('ch', 't͡ʃ', 'AOC', 1)
    koa_sounds.append(koa_ch)
    koa_chejective = Sound("ch'", 't͡ʃʼ', 'AOEC', 0.2)
    koa_sounds.append(koa_chejective)
    koa_ckh = Sound('ckh', 'q͡χ', 'AOC', 0.6)
    koa_sounds.append(koa_ckh)
    koa_ckhejective = Sound("ckh'", 'q͡χ’', 'AOEC', 0.125)
    koa_sounds.append(koa_ckhejective)

    koa_s = Sound('s', 's', 'FOC', 2)
    koa_sounds.append(koa_s)
    koa_x = Sound('x', 'ɬ', 'FOC', 1.75)
    koa_sounds.append(koa_x)
    koa_sh = Sound('sh', 'ʃ', 'FOC', 0.4)
    koa_sounds.append(koa_sh)
    koa_kh = Sound('kh', 'χ', 'FOC', 2.75)
    koa_sounds.append(koa_kh)
    koa_h = Sound('h', 'h', 'FOC', 1)
    koa_sounds.append(koa_h)

    koa_m = Sound('m', 'm', 'NC', 3)
    koa_sounds.append(koa_m)
    koa_n = Sound('n', 'n', 'NC', 4)
    koa_sounds.append(koa_n)

    koa_r = Sound('r', 'ɾ', 'LJC', 3)
    koa_sounds.append(koa_r)
    koa_l = Sound('l', 'l', 'LJC', 9)
    koa_sounds.append(koa_l)
    koa_y = Sound('y', 'ʎ', 'LJC', 2)
    koa_sounds.append(koa_y)

    koa_j = Sound('j', 'j', 'WJC', 3)
    koa_sounds.append(koa_j)
    koa_w = Sound('w', 'w', 'WJC', 1.25)
    koa_sounds.append(koa_w)

    koa_tj = Sound('tj', 'tʲ', 'SOC')
    koa_tjejective = Sound("tj'", 'tʲ’', 'SOEC')
    koa_ng = Sound('ng', 'ŋ', 'NC')

    koa_tactics = '{O,N}(2VJ)V(4{O,N})'

    koa_language = Language("Ko'a", koa_sounds, koa_tactics)

    plural = WordFormRule('Plural', 'N')
    plural.add_suffix_rule([koa_kh, koa_a], 'V')
    plural.add_suffix_rule([koa_e, koa_kh, koa_a], 'C')
    koa_language.add_word_form(plural)
    koa_language.apply_sound_change(SoundChangeRule(koa_h, koa_glottalstop, '_#'))
    koa_language.apply_sound_change(SoundChangeRule([koa_t, koa_i, koa_j], koa_tj, '_V'))
    koa_language.apply_sound_change(SoundChangeRule([koa_t, koa_e, koa_j], koa_tj, '_V'))
    koa_language.apply_sound_change(SoundChangeRule([koa_t, koa_a, koa_j], koa_tj, '_V'))
    koa_language.apply_sound_change(SoundChangeRule([koa_tejective, koa_i, koa_j], koa_tjejective, '_V'))
    koa_language.apply_sound_change(SoundChangeRule([koa_tejective, koa_e, koa_j], koa_tjejective, '_V'))
    koa_language.apply_sound_change(SoundChangeRule([koa_tejective, koa_a, koa_j], koa_tjejective, '_V'))
    genitive = WordFormRule('Genitive', 'N')
    genitive.add_suffix_rule([koa_tejective, koa_a])
    koa_language.add_word_form(genitive)
    genitive_plural = WordFormRule('Genitive Plural', 'N')  # base forms: ['Plural']
    genitive_plural.add_suffix_rule([koa_kh, koa_a], 'V')  # from plural
    genitive_plural.add_suffix_rule([koa_e, koa_kh, koa_a], 'C')  # from plural
    genitive_plural.add_suffix_rule([koa_tejective, koa_a])
    koa_language.add_word_form(genitive_plural)
    inalienable_genitive = WordFormRule('Inalienable Genitive', 'N')  # base forms: ['Genitive']
    inalienable_genitive.add_suffix_rule([koa_tejective, koa_a])  # from genitive
    inalienable_genitive.add_suffix_rule([koa_c])
    koa_language.add_word_form(inalienable_genitive)
    inalienable_genitive_plural = WordFormRule('Inalienable Genitive Plural', 'N')  # base forms: ['Genitive', 'Plural']
    inalienable_genitive_plural.add_suffix_rule([koa_kh, koa_a], 'V')  # from genitive plural
    inalienable_genitive_plural.add_suffix_rule([koa_e, koa_kh, koa_a], 'C')  # from genitive plural
    inalienable_genitive_plural.add_suffix_rule([koa_tejective, koa_a])  # from genitive plural
    inalienable_genitive_plural.add_suffix_rule([koa_c])
    koa_language.add_word_form(inalienable_genitive_plural)
    koa_language.apply_sound_change(SoundChangeRule(koa_m, koa_n, '_#'))
    koa_language.apply_sound_change(SoundChangeRule(koa_h, koa_kh))
    koa_language.apply_sound_change(SoundChangeRule(koa_u, None, 'W_C'))
    koa_language.apply_sound_change(SoundChangeRule(koa_y, koa_j))
    koa_language.apply_sound_change(SoundChangeRule(koa_c, koa_ch, '_#'))
    koa_language.apply_sound_change(SoundChangeRule(koa_cejective, koa_chejective, '_#'))
    koa_language.apply_sound_change(SoundChangeRule(koa_r, koa_n, '_C'))
    infinitive = WordFormRule('Infinitive', 'V')
    infinitive.add_prefix_rule([koa_a, koa_s])
    koa_language.add_word_form(infinitive)
    absolutive_antipassive = WordFormRule('Absolutive Antipassive', 'V')
    absolutive_antipassive.add_prefix_rule([koa_u, koa_b])
    koa_language.add_word_form(absolutive_antipassive)
    verbal_antipassive = WordFormRule('Verbal Antipassive', 'V')
    verbal_antipassive.add_prefix_rule([koa_c, koa_u])
    koa_language.add_word_form(verbal_antipassive)
    perfective = WordFormRule('Perfective', 'V')
    perfective.add_suffix_rule([koa_n, koa_i])
    koa_language.add_word_form(perfective)
    progressive = WordFormRule('Progressive', 'V')
    progressive.add_suffix_rule([koa_p, koa_a, koa_t])
    koa_language.add_word_form(progressive)
    imperative = WordFormRule('Imperative', 'V')
    imperative.add_suffix_rule([koa_b, koa_a, koa_l])
    koa_language.add_word_form(imperative)
    optative = WordFormRule('Optative', 'V')
    optative.add_suffix_rule([koa_e, koa_x], 'C')
    optative.add_suffix_rule([koa_x], 'V')
    koa_language.add_word_form(optative)
    negative = WordFormRule('Negative', 'V')
    negative.add_suffix_rule([koa_m, koa_u])
    koa_language.add_word_form(negative)
    irrealis = WordFormRule('Irrealis', 'V')
    irrealis.add_suffix_rule([koa_glottalstop, koa_o], 'V')
    irrealis.add_suffix_rule([koa_o], 'C')
    koa_language.add_word_form(irrealis)
    koa_language.apply_sound_change(SoundChangeRule(koa_n, koa_ng, '_u'))
    koa_language.apply_sound_change(SoundChangeRule([koa_n, koa_m], koa_ng))
    koa_language.apply_sound_change(SoundChangeRule(koa_u, koa_o))

    return koa_language


# noinspection SpellCheckingInspection
def generate_lleryn():
    lleryn_sounds = list()

    lleryn_i = Sound('i', 'ɪ', 'VM', 6)
    lleryn_e = Sound('e', 'ɛ', 'VM', 9)
    lleryn_e_long = Sound('ê', 'e:', 'VM', 0.03)
    lleryn_ae = Sound('æ', 'æ', 'VM', 3)
    lleryn_y = Sound('y', 'ɨ̞', 'VM', 4)
    lleryn_y_long = Sound('ŷ', 'ɨː', 'VM', 0.01)
    # lleryn_schwa = Sound('y', 'ə', 'VM', 1)
    lleryn_a = Sound('a', 'a', 'VM', 7)
    lleryn_a_long = Sound('â', 'a:', 'VM', 0.12)
    lleryn_u = Sound('u', 'ʊ', 'VM', 2)
    lleryn_u_long = Sound('û', 'u:', 'VM', 0.01)
    lleryn_o = Sound('o', 'ɔ', 'VM', 5)
    lleryn_o_long = Sound('ô', 'o:', 'VM', 0.14)
    lleryn_sounds.append(lleryn_i)
    lleryn_sounds.append(lleryn_e)
    lleryn_sounds.append(lleryn_e_long)
    lleryn_sounds.append(lleryn_ae)
    lleryn_sounds.append(lleryn_y)
    lleryn_sounds.append(lleryn_y_long)
    # lleryn_sounds.append(lleryn_schwa)
    lleryn_sounds.append(lleryn_a)
    lleryn_sounds.append(lleryn_a_long)
    lleryn_sounds.append(lleryn_u)
    lleryn_sounds.append(lleryn_u_long)
    lleryn_sounds.append(lleryn_o)
    lleryn_sounds.append(lleryn_o_long)

    lleryn_ui = Sound('ui', 'ʊi', 'VD', 0.5)
    lleryn_ei = Sound('ei', 'ɛi', 'VD', 2)
    lleryn_oi = Sound('oi', 'ɔi', 'VD', 0.2)
    lleryn_ai = Sound('ai', 'ai', 'VD', 0.5)
    lleryn_uy = Sound('uy', 'ʊɨ', 'VD', 0.01)
    lleryn_oy = Sound('oy', 'ɔɨ', 'VD', 0.01)
    lleryn_ay = Sound('ay', 'aɨ', 'VD', 0.05)
    lleryn_iu = Sound('iu', 'ɪʊ', 'VD', 0.1)
    lleryn_ou = Sound('ou', 'ɔʊ', 'VD', 0.3)
    lleryn_au = Sound('au', 'aʊ', 'VD', 1)
    lleryn_sounds.append(lleryn_ui)
    lleryn_sounds.append(lleryn_ei)
    lleryn_sounds.append(lleryn_oi)
    lleryn_sounds.append(lleryn_ai)
    lleryn_sounds.append(lleryn_uy)
    lleryn_sounds.append(lleryn_oy)
    lleryn_sounds.append(lleryn_ay)
    lleryn_sounds.append(lleryn_iu)
    lleryn_sounds.append(lleryn_ou)
    lleryn_sounds.append(lleryn_au)

    lleryn_m = Sound('m', 'm', 'C', 4)
    lleryn_n = Sound('n', 'n', 'C', 8)
    lleryn_ng = Sound('ng', 'ɲ', 'C', 0.5)
    lleryn_p = Sound('p', 'p', 'C', 1)
    lleryn_t = Sound('t', 't', 'C', 3)
    lleryn_k = Sound('k', 'k', 'C', 3)
    lleryn_b = Sound('b', 'b', 'C', 2)
    lleryn_d = Sound('d', 'd', 'C', 10)
    lleryn_g = Sound('g', 'g', 'C', 3)
    lleryn_ch = Sound('ch', 't͡ʃ', 'C', 0.6)
    lleryn_j = Sound('j', 'd͡ʒ', 'C', 0.3)
    lleryn_f = Sound('f', 'f', 'C', 3)
    lleryn_s = Sound('s', 's', 'C', 3)
    lleryn_sh = Sound('sh', 'ʃ', 'C', 0.4)
    lleryn_h = Sound('h', 'χ', 'C', 4)
    lleryn_ll = Sound('ll', 'l', 'C', 5)
    lleryn_l = Sound('l', 'j', 'C', 0.7)
    lleryn_w = Sound('w', 'w', 'C', 4)
    lleryn_r = Sound('r', 'r', 'C', 6)
    lleryn_sounds.append(lleryn_m)
    lleryn_sounds.append(lleryn_n)
    lleryn_sounds.append(lleryn_ng)
    lleryn_sounds.append(lleryn_p)
    lleryn_sounds.append(lleryn_t)
    lleryn_sounds.append(lleryn_k)
    lleryn_sounds.append(lleryn_b)
    lleryn_sounds.append(lleryn_d)
    lleryn_sounds.append(lleryn_g)
    lleryn_sounds.append(lleryn_ch)
    lleryn_sounds.append(lleryn_j)
    lleryn_sounds.append(lleryn_f)
    lleryn_sounds.append(lleryn_s)
    lleryn_sounds.append(lleryn_sh)
    lleryn_sounds.append(lleryn_h)
    lleryn_sounds.append(lleryn_ll)
    lleryn_sounds.append(lleryn_l)
    lleryn_sounds.append(lleryn_w)
    lleryn_sounds.append(lleryn_r)

    lleryn_tactics = '(7C)VC'

    lleryn_language = Language("Lleryn", lleryn_sounds, lleryn_tactics)

    return lleryn_language


def add_generated_words(language):
    nouns = language.generate_words(5, 1, 2, 'N', language_stage=0)
    language.add_words(nouns, 0)
    for noun in nouns:
        db.insert_word(noun, language.language_id)
    verbs = language.generate_words(5, 1, 2, 'V', language_stage=0)
    language.add_words(verbs, 0)
    for verb in verbs:
        db.insert_word(verb, language.language_id)


if not db.check_language_by_name("Ko'a"):
    koa = generate_koa()
    db.insert_language(koa)
    add_generated_words(koa)
    print('-'*32)
    koa.print_all_word_forms(include_ipa=True, include_base_stem=True)
else:
    koa = db.fetch_language_by_name("Ko'a")
    print('-'*32)
    koa.print_all_word_forms(include_ipa=True, include_base_stem=True)
if not db.check_language_by_name("Lleryn"):
    lleryn = generate_lleryn()
    db.insert_language(lleryn)
    add_generated_words(lleryn)
    print('-'*32)
    lleryn.print_all_word_forms(include_ipa=True, include_base_stem=True)
else:
    lleryn = db.fetch_language_by_name("Lleryn")
    print('-'*32)
    lleryn.print_all_word_forms(include_ipa=True, include_base_stem=True)
